name: GitHub Pages Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build JS artifact
        run: ./gradlew jsBrowserDistribution

      - name: List distributions
        run: ls -la build/dist/js/productionExecutable

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/dist/js/productionExecutable # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deploy branch